name: morning_alarm
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  intl: 0.16.1
  workmanager: ^0.2.0
  flutter_launcher_icons: "^0.7.3"
  flutter_local_notifications:
  weather: 0.9.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: "assets/app_icon.png"
  image_path_ios: "assets/app_icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/video_game_ringtone.mp3

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/BebasNeue-Regular.ttf

